# --- Kitty Startup Session ---

# TAB 1: Home Always(Cyberpunk Names Active)
new_tab 󱂵 HOME
cd ~
launch zsh

# TAB 2: Last Directory
new_tab 󰚗 LAST
launch zsh -c "cd \"$(cat ~/.last_kitty_dir 2>/dev/null || echo ~)\"; exec zsh"
